Use func instead of proc where appropriate
GULPF/nimquery pull request #12
Opened 2021-05-04 23:31 UTC by vabresto

Hey, thanks for this great library!

One of my favourite Nim features is the side effects tracking the compiler does, so I made these changes for my own code and wanted to share them back.

I didn't make any changes other than `proc` -> `func`. All the tests pass.

Also, VS Code warns that the various functions cannot raise `Defect` (this is new as of 1.4.0 it seems) - https://nim-lang.org/blog/2020/10/16/version-140-released.html - I thought about just removing them but that's probably better in another PR (not sure if there's any safety value in keeping them around if the compiler doesn't track it anymore). Let me know if you'd like me to include that in this PR as a general clean up.

Thanks!

2021-05-10 19:15 UTC, GULPF commented
Thanks for the contribution, seems like a good change.

> Let me know if you'd like me to include that in this PR as a general clean up.

That would be great :)

2021-05-13 02:54 UTC, vabresto commented
Wanted to follow up on this so it's not left hanging - I can't seem to be able to trigger CI runs, but the devel build seems to have failed for an unrelated reason. Is there anything waiting on me or that I can do to help?

2021-05-16 20:30 UTC, GULPF requested changes

2021-05-16 20:30 UTC, GULPF commented on nimquery.nim
> +                parts.add initQueryPart(demands, lexer.current.kind.Combinator)
This change is why the devel build is failing - Nim won't allow direct enum to enum conversions in the future. Revert this and it should work

2021-05-16 20:48 UTC, merged

2021-05-22 09:10 UTC, SolitudeSF commented
compilation now fails with `Error: 'attrComparerString' can have side effects`